# Generated by Django 4.1.2 on 2023-04-20 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adressen',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('firma', models.CharField(max_length=120)),
                ('adresse', models.CharField(max_length=200)),
                ('plz', models.CharField(max_length=20)),
                ('ort', models.CharField(max_length=100)),
                ('land', models.CharField(max_length=100)),
                ('contact', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('additional', models.CharField(blank=True, max_length=200)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Auftrag',
            fields=[
                ('auftragsnummer_ID', models.CharField(max_length=7, primary_key=True, serialize=False, unique=True)),
                ('auftraggeber', models.CharField(max_length=120)),
                ('auftragsdatum', models.DateField()),
                ('ausgeführt_bis', models.DateField()),
                ('auftrag_abgeschlossen', models.BooleanField()),
                ('auftragstext', models.TextField(blank=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('angenommen', models.BooleanField(blank=True, null=True)),
                ('auftragsfirma', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Aufträge.adressen')),
            ],
        ),
        migrations.CreateModel(
            name='Fahrer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('vorname', models.CharField(max_length=100)),
                ('nachname', models.CharField(max_length=100)),
                ('tel', models.CharField(blank=True, max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Rechnungsempfänger',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('firma', models.CharField(max_length=120)),
                ('adresse', models.CharField(max_length=200)),
                ('plz', models.CharField(max_length=20)),
                ('ort', models.CharField(max_length=100)),
                ('land', models.CharField(max_length=100)),
                ('contact', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('additional', models.CharField(blank=True, max_length=200)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rechnung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rechnungsnummer', models.CharField(max_length=7)),
                ('rechnungsdatum', models.DateField()),
                ('rechnungstext', models.TextField(blank=True)),
                ('rechnungspreis', models.FloatField(blank=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('auftragsnummer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Aufträge.auftrag')),
                ('empfänger', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Aufträge.rechnungsempfänger')),
            ],
        ),
        migrations.CreateModel(
            name='Auftragspositionen',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('position_abgeschlossen', models.BooleanField()),
                ('kostenstelle', models.CharField(blank=True, max_length=20, null=True)),
                ('einzelpreis', models.FloatField(blank=True, null=True)),
                ('unterschrift', models.URLField(blank=True, null=True)),
                ('unterschrift_datum', models.DateField(blank=True, null=True)),
                ('empfänger', models.CharField(blank=True, max_length=120, null=True)),
                ('mwst', models.IntegerField(blank=True, default=19)),
                ('anzahl', models.FloatField(blank=True, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('auftragsnummer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Aufträge.auftrag')),
                ('nach', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='nach', to='Aufträge.adressen')),
                ('von', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='von', to='Aufträge.adressen')),
            ],
        ),
        migrations.AddField(
            model_name='auftrag',
            name='fahrer',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='Aufträge.fahrer'),
        ),
    ]
