# Generated by Django 4.1.2 on 2023-04-20 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aufträge', '0002_auftragspositionen_referenz_alter_auftrag_angenommen_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Help',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frage', models.TextField()),
                ('antwort', models.TextField()),
            ],
        ),
    ]
