# Generated by Django 4.1.2 on 2023-04-24 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Aufträge', '0003_help'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auftragspositionen',
            name='auftragsnummer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Aufträge.auftrag'),
        ),
        migrations.AlterField(
            model_name='auftragspositionen',
            name='kostenstelle',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='auftragspositionen',
            name='mwst',
            field=models.IntegerField(blank=True, default=19, null=True),
        ),
        migrations.AlterField(
            model_name='auftragspositionen',
            name='nach',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='nach', to='Aufträge.adressen'),
        ),
        migrations.AlterField(
            model_name='auftragspositionen',
            name='position_abgeschlossen',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='auftragspositionen',
            name='referenz',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='auftragspositionen',
            name='von',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='von', to='Aufträge.adressen'),
        ),
    ]
