# Generated by Django 4.1.2 on 2023-04-24 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Aufträge', '0005_alter_auftragspositionen_auftragsnummer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auftragspositionen',
            name='nach',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='nach', to='Aufträge.adressen'),
        ),
        migrations.AlterField(
            model_name='auftragspositionen',
            name='von',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='von', to='Aufträge.adressen'),
        ),
    ]
