# Generated by Django 4.1.2 on 2023-04-25 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aufträge', '0006_alter_auftragspositionen_nach_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auftragspositionen',
            name='mwst',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='auftragspositionen',
            name='unterschrift',
            field=models.TextField(blank=True, null=True),
        ),
    ]
