# Generated by Django 4.1.2 on 2023-04-25 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Aufträge', '0007_alter_auftragspositionen_mwst_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auftrag',
            name='auftrag_abgeschlossen',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='auftrag',
            name='auftragsdatum',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='auftrag',
            name='auftragsfirma',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Aufträge.adressen'),
        ),
        migrations.AlterField(
            model_name='auftrag',
            name='auftragsnummer_ID',
            field=models.CharField(blank=True, max_length=7, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='auftrag',
            name='auftragstext',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='auftrag',
            name='ausgeführt_bis',
            field=models.DateField(null=True),
        ),
    ]
