# Generated by Django 4.1.2 on 2023-06-07 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aufträge', '0008_alter_auftrag_auftrag_abgeschlossen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auftrag',
            name='auftrag_abgeschlossen',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
