# Generated by Django 4.1.2 on 2023-06-07 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aufträge', '0009_alter_auftrag_auftrag_abgeschlossen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rechnung',
            name='rechnungspreis',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
